name: 02-workflow-events

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
    # branches:
      # - main
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger (event name)
        run: echo "The event name is ${{ github.event_name }} event"
      
