name: 05-1-event-filters-and-activity-types

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Filters and activity types
        run: |
          echo "Running whenever a PR is opened or synchronized and base branch is main"
          echo "The PR head ref is ${{ github.event.pull_request.head.ref }}"
          echo "The PR base ref is ${{ github.event.pull_request.base.ref }}"
          echo "The PR title is ${{ github.event.pull_request.title }}"
          echo "The PR body is ${{ github.event.pull_request.body }}"
          echo "The PR number is ${{ github.event.pull_request.number }}"
          echo "The PR author is ${{ github.event.pull_request.user.login }}"
          echo "The PR author ID is ${{ github.event.pull_request.user.id }}"
  

